--liquibase formatted sql

-- changeset mitko:create_users_table
CREATE TABLE USERS (
    ID VARCHAR(128) PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(64) NOT NULL,
    EMAIL VARCHAR(128) NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL
);

--changeset mitko:create_warranties_table
CREATE TABLE WARRANTIES (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(64) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    STATUS VARCHAR(16) NOT NULL,
    NOTE VARCHAR(2048),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,

    USER_ID VARCHAR(128) NOT NULL,
    CONSTRAINT fk_user_id FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- changeset mitko:create_warranty_files_table
CREATE TABLE FILES (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FILE TEXT NOT NULL,

    WARRANTY_ID INT NOT NULL,
    CONSTRAINT fk_warranty_id FOREIGN KEY (WARRANTY_ID) REFERENCES WARRANTIES(ID)
);

-- changeset mitko:create_user_warranty_name_index
CREATE UNIQUE INDEX idx_user_warranty_name
ON WARRANTIES (NAME, USER_ID);