spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: mtg
    password: mtg
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml