spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB