spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_schema: ${spring.datasource.schema}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/warranty_tracker
    schema: development
  security:
    oauth2:
      resourceserver:
        jwt:
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml
    default-schema: ${spring.datasource.schema}
  docker:
    compose:
      enabled: true
      file: docker/docker-compose.yml

baseUrls:
  keycloak: http://localhost:8081/realms/WarrantyTracker

keycloak:
  code-url: ${baseUrls.keycloak}/protocol/openid-connect/auth?client_id=${keycloak.client-id}&response_type=code&redirect_uri=http://localhost:5173/
  token-endpoint: ${baseUrls.keycloak}/protocol/openid-connect/token
  client-id: warranty-tracker-local
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  redirectUri: http://localhost:5173/
  admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

cloudinary:
  name: dbw5gmuas
  api-key: 951285131297993
  api-secret: ${CLOUDINARY_SECRET}