spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    url: ${DB.CONNECTION_STRING}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${baseUrls.keycloak}
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

baseUrls:
  keycloak: http://localhost:8081/realms/WarrantyTracker

keycloak:
  client-secret: ${KEYCLOAK.CLIENT_SECRET}