spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

google:
  cloud:
    credentials:
      location: classpath:google-credentials.json