spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    url: jdbc:postgresql://localhost:5432/warranty_tracker
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${baseUrls.keycloak}
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml
  docker:
    compose:
      enabled: true
      file: docker/docker-compose-dev.yml

baseUrls:
  keycloak: http://localhost:8081/realms/WarrantyTracker

keycloak:
  code-url: ${baseUrls.keycloak}/protocol/openid-connect/auth?client_id=${keycloak.client-id}&response_type=code
  token-endpoint: ${baseUrls.keycloak}/protocol/openid-connect/token
  client-id: warranty-tracker-local
  client-secret: ${KEYCLOAK.CLIENT_SECRET}
  admin-client-secret: ${KEYCLOAK.ADMIN_CLIENT_SECRET}

cloudinary:
  name: dbw5gmuas
  api-key: 951285131297993
  api-secret: ${CLOUDINARY.SECRET}