services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warranty_tracker
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d/
      - ./db-data:/var/lib/postgresql/data
    networks:
      - backend

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/warranty_tracker
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_SCHEMA: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: tempadmin
      KC_BOOTSTRAP_ADMIN_PASSWORD: tempadmin
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak-theme-for-kc-all-other-versions.jar:/opt/keycloak/providers/keycloak-theme.jar
    command: ["start-dev"]
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge
